
// This file is automatically generated.
// Please do not edit this file manually.

// This file was generated by Firebase Studio.
// You can copy and paste this directly into your main application
// but make sure to protect your secrets by using environment variables.
//
// You can get your configuration from the Firebase console.

export const firebaseConfig = {
  projectId: "petmanagement-ca50d",
  appId: "1:942453338097:web:0a8860fb70d3a771a01e50",
  apiKey: "AIzaSyCyr4ynTu_FovmNZuiAW30e6Dur239VcMY",
  authDomain: "petmanagement-ca50d.firebaseapp.com",
  messagingSenderId: "942453338097",
};
