// This file is automatically generated.
// Please do not edit this file manually.

// This file was generated by Firebase Studio.
// You can copy and paste this directly into your main application
// but make sure to protect your secrets by using environment variables.
//
// You can get your configuration from the Firebase console.

export const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};
